# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{padrino-rpm}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Florian Gilcher"]
  s.date = %q{2011-05-17}
  s.description = %q{A gem for monitoring Padrino with newrelic rpm}
  s.email = %q{florian.gilcher@asquera.de}

  s.homepage = %q{http://github.com/Asquera/padrino-rpm}
  s.require_paths = ["lib"]
  s.summary = %q{Padrino Instrumentation for New Relic RPM}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<newrelic_rpm>, [">= 3.0.0"])
    else
      s.add_dependency(%q<newrelic_rpm>, [">= 3.0.0"])
    end
  else
    s.add_dependency(%q<newrelic_rpm>, [">= 3.0.0"])
  end
end

